In [1]:
import pandas as pd

In [2]:
df_topicos = pd.read_csv("modelo_final_escolhido/df_com_topicos.csv")
df_dados = pd.read_csv("../data/preprocessed_shorts.csv")
display(df_topicos)
display(df_dados)

,id,text,Word_count,clean_text,Word_count_clean,Topico_Atribuido
0,6wQI_scenxY,"Você tem quanta altura? Eu tenho 1 em 49, mas...",172,altura falar mundo arredor passar vergonha arr...,43,3
1,INDVQhbuVco,"Cria conteúdo, vende conteúdo, manda conteúdo...",935,criar conteudo vender conteudo mandar conteudo...,343,22
2,NlfEY0f6lu4,de serviços no Jornal da Cruzeiro. Acompanhe ...,3753,servico jornal cruzeiro acompanhar jornal cruz...,1274,21
3,iXb6xOaDcLw,"Salve rapaziada aqui, o Raianço Santos e vamo...",1913,salver rapaziar raianco santo falar virginia v...,717,19
4,1pKUye91Gg8,Eu pensei que tinha fita de consumir os bagul...,332,pensar fita consumir bagulho querer incorporar...,113,31
...,...,...,...,...,...,...
6427,hALS-q8D34o,Como o ECA digital é uma solução superficial ...,165,digital solucao superficial problema rede soci...,69,36
6428,tk8elc2qLeo,"O Poucabanis, como você está, cara? Você está...",1196,poucabanis cara trabalhar cara trabalhar franc...,335,19
6429,QiAh0KvYSrg,E em meio à polêmica da regulação das redes s...,230,polemica regulacao rede social adultizacao cri...,101,1
6430,sL0CHC0qn0w,"Olá pessoal, boa noite! Tudo bem com vocês? Q...",6592,pessoal noite feira fevereiro hcomecar olhar d...,2759,21
6431,P6aT3oUL6rM,E ontem eu convencei com dois deputados marin...,649,convencei deputado marinhense autor proposta t...,261,34

,Unnamed: 0,videoId,title,channelTitle,channelId,publishedAt,description,tags,categoryId,duration,...,viewCount,likeCount,commentCount,algorithmTopics,madeForKids,defaultAudioLanguage,title_description,clean_title_description,transcription,isShorts
0,0,w22lrhGXy_I,FELCA O MELHOR XERIFE DO MM2! #roblox,Raivoso1016,UCRmBRNMStx1KTLoXZQB2MZg,2026-02-13T16:01:23Z,NaN,NaN,20,PT27S,...,529995,11403,145,"Action-adventure_game, Video_game_culture",False,pt-BR,FELCA O MELHOR XERIFE DO MM2! #roblox,felcar xerife mmroblox,"Eu sou polícia, mano. Não vou ser polícia e vo...",1
1,1,wpRkmL6Hbbo,Dep Federal Jadyel Alencar estará no Fantástic...,DynamicsThePi,UCjnfUt7Dk2wn7jeA74mk5Pw,2025-08-17T17:27:20Z,Irá comentar sobre a PL 2628/2022 que trata so...,NaN,22,PT25S,...,176,10,0,"Politics, Society",True,pt-PT,Dep Federal Jadyel Alencar estará no Fantástic...,federal jadyel alencar fantastico hoje comenta...,Estaremos hoje no Fantástico para falar do pro...,1
2,2,ZzrG8BgHoZ0,As primeiras impressões sobre o ECA Digital | ...,Olhar Digital,UCGV72aVJuWP0QPNGH4YgIww,2026-03-20T00:30:41Z,O presidente Lula assinou o decreto que oficia...,"eca digital, eca digital lula, decreto eca dig...",28,PT13M36S,...,2057,48,37,"Society, Technology",False,pt-BR,As primeiras impressões sobre o ECA Digital | ...,impressao digital leandro alvarengar president...,E esse vai ser um dos assuntos da nossa coluna...,0
3,3,glr13drvkhE,"Além do tempo, o conteúdo também importa!",Daniel Rufato,UCoJs_0AtX-Bdg9-venJ0IOg,2025-09-18T18:03:30Z,"Além do tempo de tela do seu filho, você preci...",NaN,22,PT1M12S,...,172,3,0,"Health, Video_game_culture",True,pt-PT,"Além do tempo, o conteúdo também importa! Além...",conteudo importar tela filho precisar olhar co...,Deixa eu te mostrar o que seu filho pode estar...,1
4,4,pmmwmIJZ5_k,BASEUS WM01 É BOM? O MELHOR CUSTO-BENEFÍCIO EM...,RS Eletrônicos Brasil,UC9W5_DSY-1_22WQBlhDJmsg,2025-10-18T18:16:48Z,"RS ELETRÔNICOS BRASIL | TECNOLOGIA, SEGURANÇA ...","#xaiomidelivery, #celularentrega, #realmesoroc...",28,PT24S,...,236,4,1,"Lifestyle_(sociology), Technology",False,pt-PT,BASEUS WM01 É BOM? O MELHOR CUSTO-BENEFÍCIO EM...,baseu wmcusto beneficio fone buscar discreto e...,O design dos fones de ouvido permite obter um ...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9265,9265,neLALRywe94,Não deixe nada te abalar @felquinhas #react #f...,Felca Cortado,UChFAYaVmYnFJhXXmkADjY3g,2025-11-30T06:49:22Z,Não deixe nada te abalar @felquinhas #react ...,NaN,22,PT18S,...,17867,766,19,NaN,False,pt-PT,Não deixe nada te abalar @felquinhas #react #f...,deixar abalar react felcar socialmedir marketi...,NaN,1
9266,9266,MVZZMaJzskU,Teleton 2025 | Vinhetas de Intervalo,Memória Teleton,UC5S7dJ2QxjOg_NKt5ArZ5sQ,2025-11-08T05:14:00Z,______________________________________________...,"Teleton, AACD, SBT, HEBE CAMARGO, SILVIO SANTO...",29,PT10S,...,1742,27,4,"Entertainment, Television_program",False,pt,Teleton 2025 | Vinhetas de Intervalo _________...,teleton vinheta intervalo movimento ajude tran...,NaN,0
9267,9267,L9WNPGYMPEk,O QUE É ADULTIZAÇÃO? Explicação Simples e Direta!,O que é...?,UCixFJLr8x-Lu8haNyCSXanQ,2025-08-12T17:44:57Z,📌 O que é Adultização?\nVocê sabe o que signif...,"O que é adultização, adultização infantil, adu...",27,PT2M55S,...,2562,85,1,Knowledge,False,pt-BR,O QUE É ADULTIZAÇÃO? Explicação Simples e Dire...,adultizacao explicacao simples direta adultiza...,NaN,0
9268,9268,s-Hc5BlDxqs,FELCA CANTANDO AMADO BATISTA #felca,Clipadas do Pililiu,UCGF8NkweCRdUuBj-hwAaWJQ,2025-10-01T14:18:06Z,NaN,NaN,22,PT1M1S,...,14517,1493,228,"Music, Music_of_Latin_America",False,pt-PT,FELCA CANTANDO AMADO BATISTA #felca,felcar cantar amar batista felcar,NaN,1
9269,9269,cXDCL7FWKyk,Lei Felca: 5 jogos da Riot serão bloqueados pa...,O POVO,UCj-RTZE-V3Q6jleatRR9k2A,2026-03-13T22:48:53Z,O governo dos Estados Unidos publicou nas rede...,"STF, governo Lula, notícias políticas Brasil, ...",25,PT1M47S,...,6253,161,106,Society,False,pt,Lei Felca: 5 jogos da Riot serão bloqueados pa...,felcar jogo riot bloquear pequeno newsr govern...,NaN,0

In [3]:
print(df_dados.columns)
print(df_topicos.columns)

Index(['Unnamed: 0', 'videoId', 'title', 'channelTitle', 'channelId',
       'publishedAt', 'description', 'tags', 'categoryId', 'duration',
       'caption', 'viewCount', 'likeCount', 'commentCount', 'algorithmTopics',
       'madeForKids', 'defaultAudioLanguage', 'title_description',
       'clean_title_description', 'transcription', 'isShorts'],
      dtype='object')
Index(['id', 'text', 'Word_count', 'clean_text', 'Word_count_clean',
       'Topico_Atribuido'],
      dtype='object')

In [6]:
mapa_macros = {
    # MACRO 1: Adultização e impactos
    **{i: 'Adultização e Impactos' for i in [0, 22, 37, 41]},
    # MACRO 2: Exploração e casos
    **{i: 'Exploração e Abuso' for i in [7, 29, 33, 35, 38]},
    # MACRO 3: Regulação e ECA digital
    **{i: 'Regulação e ECA Digital' for i in [1, 4, 5, 11, 26, 34, 36]},
    # MACRO 4: Privacidade e tecnologia
    **{i: 'Privacidade e Infraestrutura' for i in [17, 21, 30, 39]},
    # MACRO 5: Games e mercado
    **{i: 'Games e Mercado' for i in [2, 13, 15]},
    # MACRO 6: Roblox e mobilização
    **{i: 'Roblox e Mobilização' for i in [10, 31, 32, 45, 46, 48]},
    # MACRO 7: Felca como ator midiático
    **{i: 'Felca como Ator Midiático' for i in [9, 20, 23, 24, 44]},
    # MACRO 8: Polarização e censura
    **{i: 'Polarização e Guerra Cultural' for i in [25, 27, 28, 49]},
    # MACRO 9: Educação e prevenção
    **{i: 'Educação e Prevenção' for i in [16]},
    # MACRO 10: Ruído / Não-substantivo
    **{i: 'Ruído / Não-substantivo' for i in [3, 6, 8, 12, 14, 18, 19, 40, 42, 43, 47]}
}

df_topicos['macrotopico'] = df_topicos['Topico_Atribuido'].map(mapa_macros)

In [7]:
df_completo = pd.merge(
    df_topicos, 
    df_dados, 
    left_on='id', 
    right_on='videoId', 
    how='left'
)

colunas_para_manter = [
    'videoId', 'title', 'text', 'clean_text', 'Topico_Atribuido', 'macrotopico', 
    'channelTitle', 'channelId', 'publishedAt', 'description', 'tags', 
    'categoryId', 'duration', 'caption', 'viewCount', 'likeCount', 
    'commentCount', 'algorithmTopics', 'madeForKids', 'defaultAudioLanguage', 'isShorts'
]

df_final = df_completo[colunas_para_manter]
print(df_final.info())
display(df_final)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6432 entries, 0 to 6431
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   videoId               6432 non-null   object
 1   title                 6432 non-null   object
 2   text                  6432 non-null   object
 3   clean_text            6432 non-null   object
 4   Topico_Atribuido      6432 non-null   int64
 5   macrotopico           6432 non-null   object
 6   channelTitle          6432 non-null   object
 7   channelId             6432 non-null   object
 8   publishedAt           6432 non-null   object
 9   description           4789 non-null   object
 10  tags                  3099 non-null   object
 11  categoryId            6432 non-null   int64
 12  duration              6430 non-null   object
 13  caption               6432 non-null   bool
 14  viewCount             6432 non-null   int64
 15  likeCount             6432 non-null   int64
 16  commentCount          6432 non-null   int64
 17  algorithmTopics       6035 non-null   object
 18  madeForKids           6432 non-null   bool
 19  defaultAudioLanguage  6432 non-null   object
 20  isShorts              6432 non-null   int64
dtypes: bool(2), int64(6), object(13)
memory usage: 967.4+ KB
None

,videoId,title,text,clean_text,Topico_Atribuido,macrotopico,channelTitle,channelId,publishedAt,description,...,categoryId,duration,caption,viewCount,likeCount,commentCount,algorithmTopics,madeForKids,defaultAudioLanguage,isShorts
0,6wQI_scenxY,ela é um mini Felca #felca #altura #thaislinares,"Você tem quanta altura? Eu tenho 1 em 49, mas...",altura falar mundo arredor passar vergonha arr...,3,Ruído / Não-substantivo,Cortes do Felca,UCleQJ9xm2yk2RyE7UX6ITdA,2025-12-17T23:34:08Z,NaN,...,24,PT51S,False,16684,865,14,Lifestyle_(sociology),False,pt-PT,1
1,INDVQhbuVco,Adultização infantil: quando a criança deixa d...,"Cria conteúdo, vende conteúdo, manda conteúdo...",criar conteudo vender conteudo mandar conteudo...,22,Adultização e Impactos,Neuromood | Estimulação Magnética Transcraniana,UCzqinSUZ3syFHw1tC_fbEow,2025-12-29T21:00:19Z,No sexto e último episódio da 2ª temporada do ...,...,22,PT6M52S,False,77,1,0,Health,False,pt-PT,0
2,NlfEY0f6lu4,ECA Digital entra em vigor e acaba com a autod...,de serviços no Jornal da Cruzeiro. Acompanhe ...,servico jornal cruzeiro acompanhar jornal cruz...,21,Privacidade e Infraestrutura,Cruzeiro FM,UCmsN3HVYeq5mFih7ceYJjAw,2026-03-18T15:49:36Z,A nova lei conhecida como ECA Digital — Estatu...,...,17,PT24M28S,False,42,1,0,Society,False,pt-PT,0
3,iXb6xOaDcLw,VINI ASSUMIU A VIRGINIA - MINHA OPINIÃO,"Salve rapaziada aqui, o Raianço Santos e vamo...",salver rapaziar raianco santo falar virginia v...,19,Ruído / Não-substantivo,Raiam Santos McArn,UCYj1jy66peKPzEp808TK5ww,2025-10-28T17:03:31Z,LEIA O LIVRO PRIMEIRO MILHÃO: https://kobe.plu...,...,22,PT16M11S,False,188584,16174,1888,NaN,False,pt-BR,0
4,1pKUye91Gg8,"vídeo completo no canal, vão lá #adultização #...",Eu pensei que tinha fita de consumir os bagul...,pensar fita consumir bagulho querer incorporar...,31,Roblox e Mobilização,CATATAU,UCeiN51wCjN9rVi7wKg-Zntg,2025-09-08T22:15:31Z,NaN,...,22,PT1M23S,False,1040,34,5,Video_game_culture,False,pt-BR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6427,hALS-q8D34o,ECA DIGITAL #noticias #brasil #redessociales,Como o ECA digital é uma solução superficial ...,digital solucao superficial problema rede soci...,36,Regulação e ECA Digital,O QUE ACONTECEU?,UCGbaUkdmdEIaTzvx6HgJPNQ,2026-03-17T23:04:25Z,NaN,...,22,PT1M12S,False,352,2,0,NaN,False,pt-PT,1
6428,tk8elc2qLeo,QUEM É PAUL CABANNES SOFÁ DO FELCA,"O Poucabanis, como você está, cara? Você está...",poucabanis cara trabalhar cara trabalhar franc...,19,Ruído / Não-substantivo,Reflexos da Mente,UC39e2fWnVse0-7uENFkSATA,2025-12-01T14:55:06Z,🔥🚨Seja membro deste canal e ganhe benefícios:\...,...,24,PT8M14S,False,975,47,6,"Humour, Lifestyle_(sociology)",False,pt-BR,0
6429,QiAh0KvYSrg,INSTAGRAM VAI COMEÇAR A NOTIFICAR OS PAIS,E em meio à polêmica da regulação das redes s...,polemica regulacao rede social adultizacao cri...,1,Regulação e ECA Digital,Holz Advocacia,UCrsl5JO1dlc0dXqWIgtUiyw,2026-03-02T22:03:05Z,"O Instagram anunciou uma mudança importante, m...",...,22,PT1M18S,False,783,58,2,Society,False,pt-BR,1
6430,sL0CHC0qn0w,Ao vivo | Internet vai mudar no Brasil no mês ...,"Olá pessoal, boa noite! Tudo bem com vocês? Q...",pessoal noite feira fevereiro hcomecar olhar d...,21,Privacidade e Infraestrutura,Olhar Digital,UCGV72aVJuWP0QPNGH4YgIww,2026-02-12T23:35:14Z,"Em pouco mais de um mês, no dia 17 de março de...",...,28,PT47M21S,False,47060,3395,238,Society,False,pt-BR,0
6431,P6aT3oUL6rM,Câmara terá debate sobre proteção de menores n...,E ontem eu convencei com dois deputados marin...,convencei deputado marinhense autor proposta t...,34,Regulação e ECA Digital,Central de Notícias Brasil,UCd8k14FoIivgkHeLOCdwQFA,2025-08-14T14:22:49Z,A maior Rede de Comunicação Alternativa do Bra...,...,25,PT4M12S,False,24,3,0,"Politics, Society",False,pt-BR,0

In [8]:
tabela_formatos = pd.crosstab(
    df_final['macrotopico'], 
    df_final['isShorts'], 
    normalize='index' # Transforma em porcentagem
) * 100

print(tabela_formatos.round(1))

isShorts                          0     1
macrotopico
Adultização e Impactos         33.3  66.7
Educação e Prevenção           96.5   3.5
Exploração e Abuso             46.8  53.2
Felca como Ator Midiático      24.5  75.5
Games e Mercado                59.6  40.4
Polarização e Guerra Cultural  33.3  66.7
Privacidade e Infraestrutura   66.1  33.9
Regulação e ECA Digital        59.3  40.7
Roblox e Mobilização           23.5  76.5
Ruído / Não-substantivo        25.3  74.7

In [9]:
engajamento = df_completo.groupby('macrotopico')[['viewCount', 'likeCount', 'commentCount']].median()
engajamento = engajamento.sort_values(by='viewCount', ascending=False)

print(engajamento)

                               viewCount  likeCount  commentCount
macrotopico
Roblox e Mobilização              8380.0      209.0          20.0
Games e Mercado                   5263.0      336.0          41.0
Ruído / Não-substantivo           3391.0      107.0           6.0
Felca como Ator Midiático         2775.0       74.5           4.0
Polarização e Guerra Cultural     1172.5       33.0           2.0
Exploração e Abuso                 961.0       21.0           1.0
Privacidade e Infraestrutura       898.0       33.0           4.0
Regulação e ECA Digital            282.0        7.0           0.0
Adultização e Impactos             272.0        9.0           0.0
Educação e Prevenção               149.0        8.0           1.0

In [10]:
tabela_kids = pd.crosstab(df_completo['macrotopico'], df_completo['madeForKids'])
print(tabela_kids)

madeForKids                    False
macrotopico
Adultização e Impactos           567
Educação e Prevenção             144
Exploração e Abuso               615
Felca como Ator Midiático        632
Games e Mercado                  483
Polarização e Guerra Cultural    412
Privacidade e Infraestrutura     493
Regulação e ECA Digital         1064
Roblox e Mobilização             601
Ruído / Não-substantivo         1421

In [11]:
df_final.to_csv("../data/df_macrotopics.csv", index=False)